// Generated by https://quicktype.io

export interface Booking {
    id:            number;
    email:         string;
    bookingDate:   string;
    bookingTime:   null;
    fromPlace:     null;
    toPlace:       null;
    pickupAddress: null;
    landmark:      null;
    pickupDate:    null;
    pickupTime:    null;
    cabTypeId:     number;
    contactNo:     null;
    status:        null;
}
